# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaSistema.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(890, 650))
        MainWindow.setMaximumSize(QtCore.QSize(890, 650))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.janela = QtWidgets.QWidget(MainWindow)
        self.janela.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.janela.setObjectName("janela")
        self.frameRelogio = QtWidgets.QFrame(self.janela)
        self.frameRelogio.setGeometry(QtCore.QRect(10, 10, 141, 71))
        self.frameRelogio.setStyleSheet("border-radius: 10px;\n"
"border: 1px solid red;\n"
"")
        self.frameRelogio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRelogio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRelogio.setObjectName("frameRelogio")
        self.relogio = QtWidgets.QLabel(self.frameRelogio)
        self.relogio.setGeometry(QtCore.QRect(10, 10, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Cantarell Extra Bold")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.relogio.setFont(font)
        self.relogio.setObjectName("relogio")
        self.frameBotoesLaterais = QtWidgets.QFrame(self.janela)
        self.frameBotoesLaterais.setGeometry(QtCore.QRect(10, 90, 141, 421))
        self.frameBotoesLaterais.setStyleSheet("border: 1px solid red;\n"
"border-radius: 10px;\n"
"")
        self.frameBotoesLaterais.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBotoesLaterais.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBotoesLaterais.setObjectName("frameBotoesLaterais")
        self.buttonEntradasESaidas = QtWidgets.QPushButton(self.frameBotoesLaterais)
        self.buttonEntradasESaidas.setGeometry(QtCore.QRect(20, 10, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.buttonEntradasESaidas.setFont(font)
        self.buttonEntradasESaidas.setStyleSheet("background-color: rgb(255, 79, 25);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid green;\n"
"border-radius: 10px;\n"
"hover:{\n"
"  border: 1px solid red;\n"
"}")
        self.buttonEntradasESaidas.setObjectName("buttonEntradasESaidas")
        self.buttonEstatisticas = QtWidgets.QPushButton(self.frameBotoesLaterais)
        self.buttonEstatisticas.setGeometry(QtCore.QRect(20, 150, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.buttonEstatisticas.setFont(font)
        self.buttonEstatisticas.setStyleSheet("background-color: rgb(255, 79, 25);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border: 1px solid green;\n"
"border-radius: 10px;")
        self.buttonEstatisticas.setObjectName("buttonEstatisticas")
        self.buttonVendas = QtWidgets.QPushButton(self.frameBotoesLaterais)
        self.buttonVendas.setGeometry(QtCore.QRect(20, 80, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.buttonVendas.setFont(font)
        self.buttonVendas.setStyleSheet("background-color: rgb(255, 79, 25);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid green;\n"
"border-radius: 10px;\n"
"hover:{\n"
"  border: 1px solid red;\n"
"}")
        self.buttonVendas.setObjectName("buttonVendas")
        self.frameEntradasESaidas = QtWidgets.QFrame(self.janela)
        self.frameEntradasESaidas.setGeometry(QtCore.QRect(170, 10, 711, 501))
        self.frameEntradasESaidas.setStyleSheet("border: 1px solid red;\n"
"border-radius: 10px;\n"
"")
        self.frameEntradasESaidas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEntradasESaidas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEntradasESaidas.setObjectName("frameEntradasESaidas")
        self.formEntrada = QtWidgets.QFrame(self.frameEntradasESaidas)
        self.formEntrada.setGeometry(QtCore.QRect(10, 40, 351, 91))
        self.formEntrada.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.formEntrada.setFrameShadow(QtWidgets.QFrame.Raised)
        self.formEntrada.setObjectName("formEntrada")
        self.labelValorEntrada = QtWidgets.QLabel(self.formEntrada)
        self.labelValorEntrada.setGeometry(QtCore.QRect(10, 40, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelValorEntrada.setFont(font)
        self.labelValorEntrada.setStyleSheet("border: none;")
        self.labelValorEntrada.setObjectName("labelValorEntrada")
        self.radioButtonXbox = QtWidgets.QRadioButton(self.formEntrada)
        self.radioButtonXbox.setGeometry(QtCore.QRect(160, 30, 61, 24))
        self.radioButtonXbox.setStyleSheet("border: none;")
        self.radioButtonXbox.setObjectName("radioButtonXbox")
        self.radioButtonPc = QtWidgets.QRadioButton(self.formEntrada)
        self.radioButtonPc.setGeometry(QtCore.QRect(160, 50, 51, 24))
        self.radioButtonPc.setStyleSheet("border: none;")
        self.radioButtonPc.setObjectName("radioButtonPc")
        self.labelTituloEntrada = QtWidgets.QLabel(self.formEntrada)
        self.labelTituloEntrada.setGeometry(QtCore.QRect(150, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTituloEntrada.setFont(font)
        self.labelTituloEntrada.setStyleSheet("color: green;\n"
"border: none;")
        self.labelTituloEntrada.setObjectName("labelTituloEntrada")
        self.buttonConfirmarEntrada = QtWidgets.QPushButton(self.formEntrada)
        self.buttonConfirmarEntrada.setGeometry(QtCore.QRect(260, 30, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.buttonConfirmarEntrada.setFont(font)
        self.buttonConfirmarEntrada.setStyleSheet("background-color: rgb(255, 79, 25);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid green;\n"
"border-radius: 10px;\n"
"hover:{\n"
"  border: 1px solid red;\n"
"}")
        self.buttonConfirmarEntrada.setObjectName("buttonConfirmarEntrada")
        self.entradaValorEntrada = QtWidgets.QLineEdit(self.formEntrada)
        self.entradaValorEntrada.setGeometry(QtCore.QRect(70, 30, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.entradaValorEntrada.setFont(font)
        self.entradaValorEntrada.setStyleSheet("border: 1px solid green;")
        self.entradaValorEntrada.setObjectName("entradaValorEntrada")
        self.labelValorEntrada.raise_()
        self.radioButtonXbox.raise_()
        self.radioButtonPc.raise_()
        self.labelTituloEntrada.raise_()
        self.entradaValorEntrada.raise_()
        self.buttonConfirmarEntrada.raise_()
        self.formSaida = QtWidgets.QFrame(self.frameEntradasESaidas)
        self.formSaida.setGeometry(QtCore.QRect(380, 40, 321, 91))
        self.formSaida.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.formSaida.setFrameShadow(QtWidgets.QFrame.Raised)
        self.formSaida.setObjectName("formSaida")
        self.labelValorSaida = QtWidgets.QLabel(self.formSaida)
        self.labelValorSaida.setGeometry(QtCore.QRect(10, 40, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelValorSaida.setFont(font)
        self.labelValorSaida.setStyleSheet("border: none;")
        self.labelValorSaida.setObjectName("labelValorSaida")
        self.labelTituloSaida = QtWidgets.QLabel(self.formSaida)
        self.labelTituloSaida.setGeometry(QtCore.QRect(160, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTituloSaida.setFont(font)
        self.labelTituloSaida.setStyleSheet("border: none;\n"
"color: green;")
        self.labelTituloSaida.setObjectName("labelTituloSaida")
        self.buttonConfirmarSaida = QtWidgets.QPushButton(self.formSaida)
        self.buttonConfirmarSaida.setGeometry(QtCore.QRect(230, 30, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.buttonConfirmarSaida.setFont(font)
        self.buttonConfirmarSaida.setStyleSheet("background-color: rgb(255, 79, 25);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid green;\n"
"border-radius: 10px;\n"
"hover:{\n"
"  border: 1px solid red;\n"
"}")
        self.buttonConfirmarSaida.setObjectName("buttonConfirmarSaida")
        self.entradaValorSaida = QtWidgets.QLineEdit(self.formSaida)
        self.entradaValorSaida.setGeometry(QtCore.QRect(70, 30, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.entradaValorSaida.setFont(font)
        self.entradaValorSaida.setStyleSheet("border: 1px solid green;")
        self.entradaValorSaida.setText("")
        self.entradaValorSaida.setObjectName("entradaValorSaida")
        self.labelTitulo = QtWidgets.QLabel(self.frameEntradasESaidas)
        self.labelTitulo.setGeometry(QtCore.QRect(270, 10, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setStyleSheet("border:none;")
        self.labelTitulo.setObjectName("labelTitulo")
        self.tableWidget = QtWidgets.QTableWidget(self.frameEntradasESaidas)
        self.tableWidget.setGeometry(QtCore.QRect(10, 140, 691, 351))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.frameResumoDia = QtWidgets.QFrame(self.janela)
        self.frameResumoDia.setGeometry(QtCore.QRect(10, 520, 871, 121))
        self.frameResumoDia.setStyleSheet("border: 1px solid red;\n"
"border-radius: 10px;\n"
"")
        self.frameResumoDia.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameResumoDia.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameResumoDia.setObjectName("frameResumoDia")
        self.frameTotal = QtWidgets.QFrame(self.frameResumoDia)
        self.frameTotal.setGeometry(QtCore.QRect(10, 10, 311, 101))
        self.frameTotal.setStyleSheet("border: none;")
        self.frameTotal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTotal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTotal.setObjectName("frameTotal")
        self.labelTotal = QtWidgets.QLabel(self.frameTotal)
        self.labelTotal.setGeometry(QtCore.QRect(10, 20, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.labelTotal.setFont(font)
        self.labelTotal.setStyleSheet("border: none;")
        self.labelTotal.setObjectName("labelTotal")
        self.frameVendas = QtWidgets.QFrame(self.janela)
        self.frameVendas.setGeometry(QtCore.QRect(170, 10, 711, 501))
        self.frameVendas.setStyleSheet("border: 1px solid red;\n"
"border-radius: 10px;\n"
"")
        self.frameVendas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameVendas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVendas.setObjectName("frameVendas")
        self.formEntradaVenda = QtWidgets.QFrame(self.frameVendas)
        self.formEntradaVenda.setGeometry(QtCore.QRect(10, 40, 311, 71))
        self.formEntradaVenda.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.formEntradaVenda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.formEntradaVenda.setObjectName("formEntradaVenda")
        self.labelValorVenda = QtWidgets.QLabel(self.formEntradaVenda)
        self.labelValorVenda.setGeometry(QtCore.QRect(20, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelValorVenda.setFont(font)
        self.labelValorVenda.setStyleSheet("border: none;")
        self.labelValorVenda.setObjectName("labelValorVenda")
        self.entradaValorVenda = QtWidgets.QPlainTextEdit(self.formEntradaVenda)
        self.entradaValorVenda.setGeometry(QtCore.QRect(80, 10, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.entradaValorVenda.setFont(font)
        self.entradaValorVenda.setStyleSheet("border: 1px solid green;")
        self.entradaValorVenda.setObjectName("entradaValorVenda")
        self.buttonConfirmarEntradaVenda = QtWidgets.QPushButton(self.formEntradaVenda)
        self.buttonConfirmarEntradaVenda.setGeometry(QtCore.QRect(210, 10, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.buttonConfirmarEntradaVenda.setFont(font)
        self.buttonConfirmarEntradaVenda.setStyleSheet("background-color: rgb(255, 79, 25);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid green;\n"
"border-radius: 10px;\n"
"hover:{\n"
"  border: 1px solid red;\n"
"}")
        self.buttonConfirmarEntradaVenda.setObjectName("buttonConfirmarEntradaVenda")
        self.formFinalizarVenda = QtWidgets.QFrame(self.frameVendas)
        self.formFinalizarVenda.setGeometry(QtCore.QRect(10, 420, 691, 71))
        self.formFinalizarVenda.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.formFinalizarVenda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.formFinalizarVenda.setObjectName("formFinalizarVenda")
        self.labelRecebido = QtWidgets.QLabel(self.formFinalizarVenda)
        self.labelRecebido.setGeometry(QtCore.QRect(160, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelRecebido.setFont(font)
        self.labelRecebido.setStyleSheet("border: none;")
        self.labelRecebido.setObjectName("labelRecebido")
        self.entradaValorRecebidoVenda = QtWidgets.QPlainTextEdit(self.formFinalizarVenda)
        self.entradaValorRecebidoVenda.setGeometry(QtCore.QRect(260, 10, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.entradaValorRecebidoVenda.setFont(font)
        self.entradaValorRecebidoVenda.setStyleSheet("border: 1px solid green;")
        self.entradaValorRecebidoVenda.setPlainText("")
        self.entradaValorRecebidoVenda.setObjectName("entradaValorRecebidoVenda")
        self.buttonAdicionarValorRecebidoVenda = QtWidgets.QPushButton(self.formFinalizarVenda)
        self.buttonAdicionarValorRecebidoVenda.setGeometry(QtCore.QRect(370, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.buttonAdicionarValorRecebidoVenda.setFont(font)
        self.buttonAdicionarValorRecebidoVenda.setStyleSheet("background-color: rgb(255, 79, 25);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid green;\n"
"border-radius: 10px;\n"
"hover:{\n"
"  border: 1px solid red;\n"
"}")
        self.buttonAdicionarValorRecebidoVenda.setObjectName("buttonAdicionarValorRecebidoVenda")
        self.frameTotalVenda = QtWidgets.QFrame(self.formFinalizarVenda)
        self.frameTotalVenda.setGeometry(QtCore.QRect(10, 10, 141, 51))
        self.frameTotalVenda.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTotalVenda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTotalVenda.setObjectName("frameTotalVenda")
        self.labelTotalVenda = QtWidgets.QLabel(self.frameTotalVenda)
        self.labelTotalVenda.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTotalVenda.setFont(font)
        self.labelTotalVenda.setStyleSheet("border: none;")
        self.labelTotalVenda.setObjectName("labelTotalVenda")
        self.frameTroco = QtWidgets.QFrame(self.formFinalizarVenda)
        self.frameTroco.setGeometry(QtCore.QRect(450, 10, 151, 51))
        self.frameTroco.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTroco.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTroco.setObjectName("frameTroco")
        self.labelTroco = QtWidgets.QLabel(self.frameTroco)
        self.labelTroco.setGeometry(QtCore.QRect(10, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTroco.setFont(font)
        self.labelTroco.setStyleSheet("border: none;")
        self.labelTroco.setObjectName("labelTroco")
        self.buttonFinalizarVenda = QtWidgets.QPushButton(self.formFinalizarVenda)
        self.buttonFinalizarVenda.setGeometry(QtCore.QRect(610, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.buttonFinalizarVenda.setFont(font)
        self.buttonFinalizarVenda.setStyleSheet("background-color: rgb(255, 79, 25);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid green;\n"
"border-radius: 10px;\n"
"hover:{\n"
"  border: 1px solid red;\n"
"}")
        self.buttonFinalizarVenda.setObjectName("buttonFinalizarVenda")
        self.labelTituloVendas = QtWidgets.QLabel(self.frameVendas)
        self.labelTituloVendas.setGeometry(QtCore.QRect(330, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelTituloVendas.setFont(font)
        self.labelTituloVendas.setStyleSheet("border:none;")
        self.labelTituloVendas.setObjectName("labelTituloVendas")
        self.tabelaVendaItens = QtWidgets.QTableWidget(self.frameVendas)
        self.tabelaVendaItens.setGeometry(QtCore.QRect(10, 120, 691, 291))
        self.tabelaVendaItens.setRowCount(0)
        self.tabelaVendaItens.setColumnCount(2)
        self.tabelaVendaItens.setObjectName("tabelaVendaItens")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabelaVendaItens.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabelaVendaItens.setHorizontalHeaderItem(1, item)
        self.tabelaVendaItens.horizontalHeader().setCascadingSectionResizes(True)
        self.tabelaVendaItens.horizontalHeader().setDefaultSectionSize(334)
        self.tabelaVendaItens.horizontalHeader().setSortIndicatorShown(False)
        self.formEntradaVenda.raise_()
        self.labelTituloVendas.raise_()
        self.tabelaVendaItens.raise_()
        self.formFinalizarVenda.raise_()
        self.frameEstatisticas = QtWidgets.QFrame(self.janela)
        self.frameEstatisticas.setGeometry(QtCore.QRect(170, 10, 711, 501))
        self.frameEstatisticas.setStyleSheet("border: 1px solid red;\n"
"border-radius: 10px;\n"
"")
        self.frameEstatisticas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEstatisticas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEstatisticas.setObjectName("frameEstatisticas")
        self.labelTituloEstatisticas = QtWidgets.QLabel(self.frameEstatisticas)
        self.labelTituloEstatisticas.setGeometry(QtCore.QRect(290, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelTituloEstatisticas.setFont(font)
        self.labelTituloEstatisticas.setStyleSheet("border:none;")
        self.labelTituloEstatisticas.setObjectName("labelTituloEstatisticas")
        self.frameInicial = QtWidgets.QFrame(self.janela)
        self.frameInicial.setGeometry(QtCore.QRect(170, 10, 711, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameInicial.sizePolicy().hasHeightForWidth())
        self.frameInicial.setSizePolicy(sizePolicy)
        self.frameInicial.setStyleSheet("border: 1px solid red;\n"
"border-radius: 10px;\n"
"")
        self.frameInicial.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInicial.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInicial.setObjectName("frameInicial")
        self.labelTituloFrameInicial = QtWidgets.QLabel(self.frameInicial)
        self.labelTituloFrameInicial.setGeometry(QtCore.QRect(100, 30, 521, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelTituloFrameInicial.setFont(font)
        self.labelTituloFrameInicial.setStyleSheet("border: none;")
        self.labelTituloFrameInicial.setObjectName("labelTituloFrameInicial")
        self.calendario = QtWidgets.QCalendarWidget(self.frameInicial)
        self.calendario.setGeometry(QtCore.QRect(120, 90, 471, 281))
        self.calendario.setStyleSheet("color: rgb(0, 0, 0);")
        self.calendario.setObjectName("calendario")
        self.labelAlerta = QtWidgets.QLabel(self.frameInicial)
        self.labelAlerta.setGeometry(QtCore.QRect(210, 380, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelAlerta.setFont(font)
        self.labelAlerta.setStyleSheet("border: none;")
        self.labelAlerta.setObjectName("labelAlerta")
        self.frameRelogio.raise_()
        self.frameBotoesLaterais.raise_()
        self.frameResumoDia.raise_()
        self.frameEstatisticas.raise_()
        self.frameEntradasESaidas.raise_()
        self.frameVendas.raise_()
        self.frameInicial.raise_()
        MainWindow.setCentralWidget(self.janela)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de gestão para lan houses"))
        self.relogio.setText(_translate("MainWindow", "00:00:00"))
        self.buttonEntradasESaidas.setText(_translate("MainWindow", "ENTRADAS \n"
" E \n"
" SAIDAS"))
        self.buttonEstatisticas.setText(_translate("MainWindow", "ESTATISTICAS"))
        self.buttonVendas.setText(_translate("MainWindow", "VENDAS"))
        self.labelValorEntrada.setText(_translate("MainWindow", "Valor:"))
        self.radioButtonXbox.setText(_translate("MainWindow", "xbox"))
        self.radioButtonPc.setText(_translate("MainWindow", "pc"))
        self.labelTituloEntrada.setText(_translate("MainWindow", "ENTRADA"))
        self.buttonConfirmarEntrada.setText(_translate("MainWindow", "CONFIRMAR"))
        self.labelValorSaida.setText(_translate("MainWindow", "Valor:"))
        self.labelTituloSaida.setText(_translate("MainWindow", "SAIDA"))
        self.buttonConfirmarSaida.setText(_translate("MainWindow", "CONFIRMAR"))
        self.labelTitulo.setText(_translate("MainWindow", "ENTRADAS E SAIDAS"))
        self.labelTotal.setText(_translate("MainWindow", "Total:"))
        self.labelValorVenda.setText(_translate("MainWindow", "Valor:"))
        self.buttonConfirmarEntradaVenda.setText(_translate("MainWindow", "ADICIONAR"))
        self.labelRecebido.setText(_translate("MainWindow", "Recebido:"))
        self.buttonAdicionarValorRecebidoVenda.setText(_translate("MainWindow", "ADICIONAR"))
        self.labelTotalVenda.setText(_translate("MainWindow", "Total:"))
        self.labelTroco.setText(_translate("MainWindow", "Troco:"))
        self.buttonFinalizarVenda.setText(_translate("MainWindow", "FINALIZAR"))
        self.labelTituloVendas.setText(_translate("MainWindow", "VENDAS"))
        item = self.tabelaVendaItens.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "VALOR"))
        item = self.tabelaVendaItens.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "OBSERVAÇÕES"))
        self.labelTituloEstatisticas.setText(_translate("MainWindow", "ESTATISTICAS"))
        self.labelTituloFrameInicial.setText(_translate("MainWindow", "Sistema de gestão para Lan Houses"))
        self.labelAlerta.setText(_translate("MainWindow", "CONFIRA DATA E HORA!"))

import resources_rc
